# Generated by Django 5.1 on 2025-01-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
