# Generated by Django 5.0.6 on 2024-07-31 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='connect_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='connect_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subchannel',
            name='connect_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subchannel',
            name='open',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChannelMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Requested'), (1, 'Active'), (2, 'Inactive'), (3, 'Suspended'), (4, 'Amitted'), (5, 'Blocked'), (6, 'Removed'), (7, 'Following')], null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_member', to='community.channel')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_member_permission', to='community.permissionassignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this_channel_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubChannelGroupMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Requested'), (1, 'Active'), (2, 'Inactive'), (3, 'Suspended'), (4, 'Amitted'), (5, 'Blocked'), (6, 'Removed'), (7, 'Following')], null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_channel_group_member', to='community.group')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_channel_group_member_permission', to='community.permissionassignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this_sub_channel_group_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubChannelMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Requested'), (1, 'Active'), (2, 'Inactive'), (3, 'Suspended'), (4, 'Amitted'), (5, 'Blocked'), (6, 'Removed'), (7, 'Following')], null=True)),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_channel_member_permission', to='community.permissionassignment')),
                ('sub_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_channel_member', to='community.subchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this_sub_channel_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
