# Generated by Django 5.0.6 on 2024-07-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_channel_connect_link_channel_open_group_connect_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subchannelgroupmembers',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Requested'), (1, 'Active'), (2, 'Inactive'), (3, 'Suspended'), (4, 'Amitted'), (5, 'Blocked'), (6, 'Removed'), (7, 'Following'), (8, 'Un-followed'), (9, 'Inactive'), (10, 'connected'), (11, 'disconnected')], null=True),
        ),
    ]
