# Generated by Django 5.0.6 on 2024-08-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_subchannelgroupmembers_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='blocked_members',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='members',
        ),
        migrations.RemoveField(
            model_name='channelmembers',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='group',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='group',
            name='blocked_members',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='permissionassignment',
            name='members',
        ),
        migrations.RemoveField(
            model_name='subchannel',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='subchannel',
            name='blocked_members',
        ),
        migrations.RemoveField(
            model_name='subchannel',
            name='members',
        ),
        migrations.AlterField(
            model_name='channelmembers',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Requested'), (1, 'Active'), (2, 'Inactive'), (3, 'Suspended'), (4, 'Amitted'), (5, 'Blocked'), (6, 'Removed'), (7, 'Following'), (8, 'Un-followed'), (9, 'Inactive'), (10, 'connected'), (11, 'disconnected')], null=True),
        ),
        migrations.AlterField(
            model_name='channelmembers',
            name='type',
            field=models.TextField(blank=True, default='member', null=True),
        ),
        migrations.AlterField(
            model_name='permissionassignment',
            name='permission_type',
            field=models.CharField(default='member', max_length=120),
        ),
        migrations.AlterField(
            model_name='subchannelmembers',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Requested'), (1, 'Active'), (2, 'Inactive'), (3, 'Suspended'), (4, 'Amitted'), (5, 'Blocked'), (6, 'Removed'), (7, 'Following'), (8, 'Un-followed'), (9, 'Inactive'), (10, 'connected'), (11, 'disconnected')], null=True),
        ),
    ]
