# Generated by Django 5.0.6 on 2024-08-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_channel_admins_remove_channel_blocked_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subchannel',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
