# Generated by Django 5.1 on 2024-08-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_invitelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmembers',
            name='type',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
