# Generated by Django 5.1 on 2024-09-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_channelmembers_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='target_type',
            field=models.CharField(blank=True, choices=[('community', 'Community'), ('sub-community', 'Sub-community'), ('group', 'Group')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='channelmembers',
            name='type',
            field=models.TextField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission_type',
            field=models.IntegerField(choices=[(0, 'Update Community'), (1, 'Add Members'), (2, 'Grant Sub-community Access'), (3, 'Ban Members'), (4, 'Remove Members'), (5, 'Create Sub-communities'), (6, 'Update Sub-communities'), (7, 'Delete Sub-communities'), (8, 'Create Groups'), (9, 'Update Groups'), (10, 'Delete Groups'), (11, 'Grant Group Access'), (12, 'Create Community Roles'), (13, 'Create Sub-community Roles'), (14, 'Create Group Roles'), (15, 'Mute Members'), (16, 'Set Group Messaging Status')]),
        ),
    ]
