# Generated by Django 5.1 on 2024-09-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_permission_target_type_alter_channelmembers_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='exception_users',
        ),
    ]
