# Generated by Django 5.1 on 2024-09-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_mfa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subchannelmembers',
            name='permission',
        ),
        migrations.AlterField(
            model_name='subchannelmembers',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Requested'), (1, 'Active'), (2, 'Inactive'), (3, 'Suspended'), (4, 'Admitted'), (5, 'Blocked'), (6, 'Removed'), (7, 'Following'), (8, 'Un-followed'), (9, 'Inactive'), (10, 'Connected'), (11, 'Disconnected')], null=True),
        ),
        migrations.AlterField(
            model_name='subchannelmembers',
            name='type',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
