# Generated by Django 5.1 on 2024-09-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_remove_subchannelmembers_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subchannelgroupmembers',
            name='permission',
        ),
    ]
