# Generated by Django 5.1 on 2024-10-04 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_events_formquestion_formoption_formquestion2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.channel'),
        ),
    ]
