# Generated by Django 5.1 on 2024-10-04 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_remove_formquestion_event_remove_formquestion2_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eventPaymentLink', models.CharField(blank=True, max_length=255, null=True)),
                ('paymentMethod', models.CharField(blank=True, max_length=50, null=True)),
                ('allowJoinChannel', models.BooleanField(default=False)),
                ('requireForm', models.BooleanField(default=False)),
                ('requireAttendeeForm', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_channel', to='community.channel')),
            ],
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('structural', 'Structural'), ('essay', 'Essay')], max_length=50)),
                ('wordLimit', models.CharField(blank=True, max_length=255)),
                ('correctOption', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formQuestions', to='community.events')),
            ],
        ),
        migrations.CreateModel(
            name='FormOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='community.formquestion')),
            ],
        ),
        migrations.CreateModel(
            name='FormQuestion2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('structural', 'Structural'), ('essay', 'Essay')], max_length=50)),
                ('wordLimit', models.CharField(blank=True, max_length=255)),
                ('correctOption', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formQuestions2', to='community.events')),
            ],
        ),
        migrations.CreateModel(
            name='FormOption2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='community.formquestion2')),
            ],
        ),
    ]
