# Generated by Django 5.1 on 2024-10-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_events_formquestion_formoption_formquestion2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('DRAFT', 'Draft')], default='ACTIVE', max_length=20),
        ),
    ]
