# Generated by Django 5.1 on 2024-10-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_remove_events_is_deleted_events_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formquestion2',
            name='event',
        ),
        migrations.RemoveField(
            model_name='formquestion',
            name='event',
        ),
        migrations.RemoveField(
            model_name='formoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='formoption2',
            name='question',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='FormOption',
        ),
        migrations.DeleteModel(
            name='FormQuestion',
        ),
        migrations.DeleteModel(
            name='FormOption2',
        ),
        migrations.DeleteModel(
            name='FormQuestion2',
        ),
    ]
