# Generated by Django 5.1 on 2024-10-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('paid', 'Paid')], max_length=100, null=True),
        ),
    ]
