# Generated by Django 5.1 on 2024-10-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_events_date_alter_events_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='question',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='formquestion2',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
