# Generated by Django 5.0.1 on 2024-02-15 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_channel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='subchannel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_group', to='channels.subchannel'),
        ),
        migrations.AlterField(
            model_name='subchannel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subchannel', to='channels.channel'),
        ),
    ]
