# Generated by Django 5.0.1 on 2024-02-15 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_user_alter_group_subchannel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='admins',
            field=models.ManyToManyField(related_name='admin_users_channel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_users_channel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(related_name='admin_users_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_users_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subchannel',
            name='admins',
            field=models.ManyToManyField(related_name='admin_users_subchannel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subchannel',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_users_subchannel', to=settings.AUTH_USER_MODEL),
        ),
    ]
