# Generated by Django 5.0.1 on 2024-02-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_remove_channel_allowed_users_remove_channel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permission_type',
            field=models.IntegerField(choices=[('Delete', 'Delete'), ('Create', 'Create'), ('Update', 'Update'), ('Is super admin', 'Is super admin'), ('Can add member', 'Add member'), ('Can remove member', 'Remove member')]),
        ),
    ]
