# Generated by Django 5.0.1 on 2024-02-27 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_alter_permission_permission_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionassignment',
            name='members',
            field=models.ManyToManyField(related_name='Permission_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permissionassignment',
            name='permission_type',
            field=models.CharField(max_length=120),
        ),
    ]
