# Generated by Django 4.1.5 on 2024-01-29 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='country_code_data',
            new_name='code',
        ),
    ]
