# Generated by Django 4.1.5 on 2024-04-27 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_online', models.IntegerField(choices=[(0, 'Everyone'), (1, 'MyContacts'), (2, 'MyContactsExcept'), (3, 'Nobody')], default=0)),
                ('profile_photo', models.IntegerField(choices=[(0, 'Everyone'), (1, 'MyContacts'), (2, 'MyContactsExcept'), (3, 'Nobody')], default=0)),
                ('about', models.IntegerField(choices=[(0, 'Everyone'), (1, 'MyContacts'), (2, 'MyContactsExcept'), (3, 'Nobody')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Everyone'), (1, 'MyContacts'), (2, 'MyContactsExcept'), (3, 'Nobody')], default=0)),
                ('groups', models.IntegerField(choices=[(0, 'Everyone'), (1, 'MyContacts'), (2, 'MyContactsExcept'), (3, 'Nobody')], default=0)),
                ('calls', models.IntegerField(choices=[(0, 'Everyone'), (1, 'MyContacts'), (2, 'MyContactsExcept'), (3, 'Nobody')], default=0)),
                ('disappearing_messages', models.IntegerField(choices=[(24, '24 hours'), (7, '7 days'), (30, '30 days'), (90, '90 days'), (0, 'off')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyExceptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_type', models.CharField(max_length=100, null=True)),
                ('exceptions', models.ManyToManyField(blank=True, related_name='privacy_exceptions', to=settings.AUTH_USER_MODEL)),
                ('privacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_exceptions', to='user.privacysettings')),
            ],
        ),
    ]
