# Generated by Django 4.1.5 on 2024-04-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_privacysettings_privacyexceptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacysettings',
            name='groups',
            field=models.BooleanField(default=False),
        ),
    ]
