# Generated by Django 4.1.5 on 2024-05-02 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_privacysettings_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(choices=[(0, 'Never'), (1, 'Only_when_I_tap'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
                ('include_videos', models.BooleanField(default=True)),
                ('cellula', models.BooleanField(default=True)),
                ('end_to_end', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light', models.BooleanField(default=True)),
                ('darck', models.IntegerField(max_length=50, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='wallpaper/')),
                ('default', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.IntegerField(choices=[(0, 'Default'), (1, 'Light'), (2, 'Dark')], default=0)),
                ('enter', models.BooleanField(default=False)),
                ('media', models.BooleanField(default=True)),
                ('Font_size', models.IntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Larg')], default=1)),
                ('archived', models.BooleanField(default=True)),
                ('archive_all_chats', models.BooleanField(default=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup', to='user.backup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ChatSettings', to=settings.AUTH_USER_MODEL)),
                ('wallpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallpaper', to='user.wallpaper')),
            ],
        ),
    ]
