# Generated by Django 4.1.5 on 2024-05-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_backup_wallpaper_chatsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='darck',
            field=models.IntegerField(null=True),
        ),
    ]
