# Generated by Django 5.1 on 2025-01-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='publicKey',
            field=models.TextField(blank=True, null=True),
        ),
    ]
