# Generated by Django 5.1 on 2025-01-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_publickey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallpaper',
            old_name='darck',
            new_name='dark',
        ),
        migrations.RemoveField(
            model_name='chatsettings',
            name='Font_size',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='chatsettings',
            name='font_size',
            field=models.IntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large')], default=1),
        ),
    ]
