# Generated by Django 5.1 on 2025-01-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_darck_wallpaper_dark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallpaper',
            old_name='dark',
            new_name='darck',
        ),
        migrations.RemoveField(
            model_name='chatsettings',
            name='font_size',
        ),
        migrations.AddField(
            model_name='chatsettings',
            name='Font_size',
            field=models.IntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Larg')], default=1),
        ),
    ]
